version: '3'
services:
  webapp1:
    build: .
    ports:
      - "8001:80"
    networks:
      - networkName
  webapp2:
    build: .
    ports:
      - "8002:80"
    networks:
      - networkName
  webapp3:
    build: .
    ports:
      - "8003:80"
    networks:
      - networkName

networks:
  networkName:
    driver: bridge
